---
openapi: 3.0.3
info:
  title: onecx-help v1 service
  version: 1.0.0
servers:
  - url: "http://onecx-help-svc:8080"
tags:
  - name: helpsV1
paths:
  /v1/helps/{appId}/{helpItemId}:
    get:
      tags:
        - helpsV1
      description: search help item by criteria
      operationId: searchHelpItem
      parameters:
        - name: appId
          in: path
          required: true
          description: application ID
          schema:
            type: string
        - name: helpItemId
          in: path
          required: true
          description: help item ID
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Help'
        404:
          description: Help not found
components:
  schemas:
    Help:
      required:
        - itemId
      type: object
      properties:
        itemId:
          type: string
        context:
          type: string
        baseUrl:
          type: string
        resourceUrl:
          type: string
        appId:
          type: string
