---
openapi: 3.0.3
info:
  title: onecx-help data import service
  description: template import from file during the start of the application
  version: 1.0.0
servers:
  - url: "http://localhost"
paths:
  /import/help:
    post:
      operationId: importHelp
      description: Import help from template
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TemplateImport'
      responses:
        200:
          description: Help imported successfully
components:
  schemas:
    TemplateImport:
      type: object
      properties:
        helps:
          $ref: '#/components/schemas/TemplateProductHelp'
    TemplateProductHelp:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/TemplateHelp'
    TemplateHelp:
      type: object
      nullable: false
      additionalProperties:
        $ref: '#/components/schemas/TemplateHelpItem'
    TemplateHelpItem:
      type: object
      properties:
        context:
          type: string
        baseUrl:
          type: string
        resourceUrl:
          type: string